# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/gsrs_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# App
spring.application.name=GSRS
server.port=8080

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
# 24 hrs

# Disable spring default security
spring.security.user.name=disable
spring.security.user.password=disable