# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# App
spring.application.name=GSRS
server.port=${PORT:8080}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Disable spring default security
spring.security.user.name=disable
spring.security.user.password=disable